# Generated by Django 2.1.7 on 2019-05-13 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('publication_date', models.DateTimeField()),
                ('anonimus', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('discarded', models.BooleanField(default=False)),
                ('quantity_positive_votes', models.IntegerField(blank=True, null=True)),
                ('quantity_negative_votes', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='photo/user.png', null=True, upload_to='media/photo/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appIdeas.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Votes_Realized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative')], max_length=10)),
                ('id_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appIdeas.Idea')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
