# Generated by Django 2.1.7 on 2019-05-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIdeas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='photo',
            field=models.ImageField(blank=True, default='media/photo/user.png', null=True, upload_to='media/photo/'),
        ),
    ]
