# Generated by Django 2.1.7 on 2019-05-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIdeas', '0003_auto_20190515_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='unique_name_category',
            new_name='category',
        ),
    ]
