# Generated by Django 2.1.7 on 2019-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIdeas', '0004_auto_20190515_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='id',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='unique_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
