# Generated by Django 2.1.7 on 2019-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIdeas', '0006_auto_20190515_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
    ]
