# Generated by Django 2.1.7 on 2019-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIdeas', '0008_idea_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_validate_idea', 'Puede Validar Ideas'),),
            },
        ),
    ]
